# Generated by Django 2.2 on 2019-04-06 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('base_price', models.IntegerField(default=0)),
                ('status', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TName', models.CharField(max_length=200)),
                ('balance', models.IntegerField()),
                ('player_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sold_Players',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_price', models.IntegerField()),
                ('TName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iplapp.Team')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iplapp.Player')),
            ],
        ),
    ]
